name: 'user-web'
port: 8021
user_srv:
  host: '127.0.0.1'
  port: 50051

jwt:
  key: 'ud#a!TPZjfe2ugENILvbF8XVQiCAWybN'

sms:
  key: 'LTAI4G51XfNdzm77KsLiZ8PD'
  secret: 'dRCvgFgvYs0FaioPInHP5lCJkmE6PD'
  expire: 300

redis:
  host: '192.168.20.20'
  port: 6379