name: 'user-web'
port: 8021
user_srv:
  host: '192.168.1.9'
  port: 50051
  name: 'user-srv'

jwt:
  key: 'ud#a!TPZjfe2ugENILvbF8XVQiCAWybN'

sms:
  key: ''
  secret: ''
  expire: 300

redis:
  host: '192.168.20.20'
  port: 6379

consul:
  host: '192.168.20.20'
  port: 8500