name: 'user-web'
port: 8021
user_srv:
  host: '127.0.0.1'
  port: 50051

jwt:
  key: 'ud#a!TPZjfe2ugENILvbF8XVQiCAWybN'

sms:
  key: 'LTAI4GEry7zodh28CpQcz5Pc'
  secret: 'UZASoLvhtY2Ei8j2rMPCJif4noSl5u'
  expire: 300

redis:
  host: '192.168.20.20'
  port: 6379